### ISSUE TITLE
Dependencies on source directory / relocatability lost

### ISSUE THREAD

**Issue by olifre** [vmc-project/geant4_vmc#13]
Dear Ivana,

since https://github.com/vmc-project/geant4_vmc/commit/d11d16421b965211d64a59bca1b50e51302b8147 it seems that the installed PCM references source paths at runtime which were only available during build time. 

To better explain, here's what I see:
```
libgeant4vmc dictionary payload:44:10: fatal error: '/var/tmp/portage/sci-physics/geant-vmc-9999/work/geant-vmc-9999/source/run/include/TG4RunConfiguration.h' file not found
#include "/var/tmp/portage/sci-physics/geant-vmc-9999/work/geant-vmc-9999/source/run/include/TG4RunConfiguration.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   <ERROR> 2020-04-21 00:11:43 <ROOT-TInterpreter::A>(not set )  Error parsing payload code for class TG4RunConfiguration with content:
```

That's after compiling with:
`/var/tmp/portage/sci-physics/geant-vmc-9999/work/geant-vmc-9999` being the source directory and
`/var/tmp/portage/sci-physics/geant-vmc-9999/work/geant-vmc-9999_build` being the build directory. 
I purge both directories after installation (I used `-DCMAKE_INSTALL_PREFIX=/usr`) but the installed PCM is still referencing the source location valid at build-time instead of referencing the installed sources or honouring `ROOT_INCLUDE_PATH`. 

You can easily reproduce by using a temporary source and build directory, installing to a prefix, and afterwards running:
```
root[0] TGeant4
```
which will immediately trigger the issue. 

Sadly, I am not an expert of the CMake macros shipped with ROOT...

**Comment by olifre** [comment]
Hi @ihrivnac , 

@amadio has pointed out this backwards-incompatible change in the release notes of ROOT 6.18:
https://root.cern/doc/v618/release-notes.html#header-location-and-root_generate_dictionary-root_standard_library_package
Indeed, this very much looks like the cause. The old CMake code (for which I developed the PCM generation parts) always passed relative paths to `rootcling`, which made things work well. 
However, it seems that now the paths as CMake has them (absolute by default) are passed to the macros, causing that issue.

**Comment by olifre** [comment]
Looking at this, a fix is not too easy using the ROOT-provided macros. 
They seem to rely upon the relative path given during compilation matching the path during runtime later, i.e. if I understand correctly, it would be necessary to reorganize the repository to match the structure present after installation.

**Comment by amadio** [comment]
@Axel-Naumann, should an issue be opened for this in ROOT? Requiring source code be organized the same as in the installation path doesn't sound that reasonable.

**Comment by olifre** [comment]
Of course, it might also be my understanding of the macros is wrong, so if that's not the case, feel free to correct me :-).

**Comment by Axel-Naumann** [comment]
Using `rootcling -Ibuildpath some/dir/File.h` should fix this, where `buildpath` should not play a role at runtime, but `some/dir/File.h` is expected to be "findable" at runtime. Makes sense?

**Comment by ihrivnac** [comment]
@olifre ,@Axel-Naumann , 
Since the update mentioned above we use ROOT_GENERATE_DICTIONARY macro from ROOT to generate dictionaries. If I change the call to this macro as suggested at the release notes, we get rid off the hardcoded path to the includes in the source directory, but then the users will have to set the path to the includes as described in 9.4.2:
https://root.cern.ch/root/htmldoc/guides/users-guide/Cling.html
@olliffre, will this change solve your issue?

**Comment by olifre** [comment]
@ihrivnac I think there are basically three options:
1. Drop the path completely and include the files directly (i.e. as the release notes suggest). 
    - Advantage: No changes to any structure needed. 
    - Disadvantages: It requires all users of the libraries to adapt `ROOT_INCLUDE_DIR` to include `g4root`, `geant4vmc`, `mtroot` (and for the other libraries, such as `vmc`, also the corresponding directory). This will fill up the `ROOT_INCLUDE_DIR` quite a lot. In any case, with the curren reorganisation of install paths, all consumers of these libraries need to change their way they include it. 
2. Use a relative include path such as `geant4vmc/`, `g4root/` etc. prefixed to that when calling `ROOT_GENERATE_DICTIONARY`. This matches the install path, i.e. if installed to `/usr/include/` or another path which already is in `ROOT_INCLUDE_DIR`, it will work immediately, without bloating `ROOT_INCLUDE_DIR` additionally. One might also argue consumers of the libraries should adapt their `#include` statements to include these prefixes. Here, there two sub-options:
    a. Keep the current repository structure as it is, and somehow make `geant4vmc/TGeant4.h` work without reorganizing it (e.g. with symlinks). `-Ibuildpath` can help here as @Axel-Naumann  suggested. 
    b. Reorganize the repository to reflect the new structure used during installation, i.e. group the includes which are installed for `geant4vmc` into a subdirectory called exactly that. 

In any case, all existing software needs changes, both since the install location of the headers has been changed (now, subdirectories are used), so we should consider this a breaking change in any case and think freely which is the best way to go. 
I personally tend to the latter option, but I'm not sure if it really is the best one in the long run.

**Comment by ihrivnac** [comment]
@olifre , @Axel-Naumann ,
Another solution could be to use `-inlineInputHeader` option when creating the dictionaries, that avoids the need to provide a path at runtime. 
@Axel-Naumann , is there any penalty which could this involve?

**Comment by olifre** [comment]
@ihrivnac : I also thought this was a good idea in 2014:
https://sft.its.cern.ch/jira/browse/ROOT-6468
However, there are several issues with it:
- It only works for a single header file. So it will not fix this problem, unless you play fancy tricks like ensuring included headers do not overlap and concatenating them together (e.g. temporarily during build with CMake). I tried that at some point, it has advantages (the compiler can optimize better) but comes with many disadvantages on its own. So I discarded this idea later on. 
- You will get really ugly issues if the installed header file (used by other programs linking against `geant-vmc`) and the header file embedded in the PCM ever disagree. 

Maybe there are other downsides, but @Axel-Naumann will know better ;-).

**Comment by ihrivnac** [comment]
The `-inlineInputHeader` option is somehow used in the ALICE O2 CMake files, where it works.
 But it failed when I simply tried to add it in the ROOT_GENERATE_DICTIONARY call in the Geant4 VMC CMake files.

I am adding @aphecetche (who developed our current CMake build system) if he could help here.

**Comment by olifre** [comment]
Reading through:
https://github.com/root-project/root/blob/f90a7e49c6e4007ceff0814d22354de1cae733d7/core/dictgen/src/rootcling_impl.cxx#L3772-L3777
it does not really seem this option is meant for production use. 

It seems ALICE O2 inherited this command from FairROOT legacy, it first came in as of this PR:
https://github.com/AliceO2Group/AliceO2/pull/75

FairROOT has removed it in 2018 again:
https://github.com/FairRootGroup/FairRoot/pull/722
They actually referenced  https://sft.its.cern.ch/jira/browse/ROOT-6468 there, and decided that since this parameter is neither used by the ROOT project nor used by them (relative include paths everywhere) they never really needed it. 

Judging from this history, it seems this flag did probably not enter into Alice O2 on purpose, but was a collateral change from the FairROOT inheritance, maybe @aphecetche can add more insight on this.

**Comment by aphecetche** [comment]
Well, to make a really useful answer I'd need to dig more through this issue, and I'm afraid I don't really have the time at the moment.

What I can say though about the `-inlineInputHeader` is that a) it's still in use in FairRoot as far as I can tell (see [generate_dictionary_root_sh.in](https://github.com/FairRootGroup/FairRoot/blob/dev/cmake/scripts/generate_dictionary_root.sh.in )) b) it's indeed used in AliceO2, because it was in FairRoot, yes, probably (can't really remember) and because it's working for us ;-)

Now, for full disclosure I would add that the way we generate dictionaries in AliceO2 (see [AddRootDictionary.cmake](https://github.com/AliceO2Group/AliceO2/blob/dev/cmake/AddRootDictionary.cmake) and [rootcling_wrapper.sh.in](  https://github.com/AliceO2Group/AliceO2/blob/dev/cmake/rootcling_wrapper.sh.in)) is probably not 100% correct. We discovered recently that we do seem to have some cases where an incremental build fails to pick-up some PCM dependencies. We have an issue opened on that, that I still have to investigate...

**Comment by olifre** [comment]
> and because it's working for us ;-)

@aphecetche What exactly does "working for us" mean? 
As far as I see, both FairROOT and Alice O2 use relative paths everywhere in dictionary generation, which means that neither the limitation that headers are not found due to absolute paths nor the problem that only a single header is embedded apply here. So unless I misread the code, it seems to me that the parameter is not relied upon, or is it?

**Comment by aphecetche** [comment]
we do use relative paths in our CMakeLists.txt, yes,  but in the end the rootcling invocation uses full paths. I'm attaching one such invocation that's generated by our CMake system, if it can makes things clearer.  
[cmd.txt](https://github.com/vmc-project/geant4_vmc/files/4515115/cmd.txt)

**Comment by olifre** [comment]
@aphecetche Interesting! Then I wonder how exactly this works at runtime when the source files are purged, that would either mean the `-inlineInputHeader` option is now actually doing an umbrella header instead and inlining them all, or there has been another change to `rootcling` which "fixes" this model, but is not yet documented... 

@Axel-Naumann : Do you have an explanation why this command seems to inline all headers, and why this seems to work without issues for Alice?

**Comment by ihrivnac** [comment]
In ALICE tests, we set `ROOT_INCLUDE_PATH`, so it could be that the  `-inlineInputHeader` option does actually nothing as the headers are retrieved from the packages installations.

I think that the most straightforward solution will be your option 1.  The advantage, in addition to yours, is that this is the way recommended by ROOT, so we can expect that it will be followed by most users. Note that `g4root` and `mtroot` do not contain any dictionaries, so at the end using the VMC packages in macros will require just adding two include paths:  `vmc` and `geant4vmc`.

I'd not completely exclude your option 2a, which could be provided optionally (via a cmake option), but I will not have time to work on it in a short term.

**Comment by ChristianTackeGSI** [comment]
Hi,
(Ivana invited me. Thanks again!)
I had basicly the same problem with vmc and looked a bit deeper into what is happening there and came up with some conclusions for our packaging.

### How things work together

A quick intro on how things work together (at least, as I have understood it by looking at the ROOT 6.18 source, experts will hopefully correct me):
* When I write `rootcling` I usualy mean: `rootcling` or `ROOT_GENERATE_DICTIONARY` which will finally call `rootcling`.
* The header paths as given to `rootcling` are stored in the generated dictionary as-is. So anything from absolute to `sub1/thing2.h` to just `thing3.h` will just be stored.
* Inside the dictionary is a list of paths. It will be populated using the `-I` arguments to `rootcling` (will be generated from cmake's `include_directories()` in the macro).
* Any entry in this list matched by an argument to `rootcling`'s `-excludePath` (can be passed using the `OPTIONS` argument to `ROOT_GENERATE_DICTIONARY`) will be removed from the list. Matching means prefix-matching in this case.
* This list can be seen in the generated `*_dict.cxx` as `includePaths`.
* When the module (`.so`) is loaded in the ROOT interpreter, the dictionary's path list is appended to the current include path list of the interpreter (as seeded from `$ROOT_INCLUDE_PATH`).
* Then each header is loaded using its stored name. So if it is absolute, then it will be searched in that absolute path. Otherwise each entry in the current include search list is tried for the relative path.

### First conclusions

* Storing an absolute path isn't a good idea, generally. As there is no flexibility and if the stored path is in the source/build tree, then things will fail, when the source/build tree is removed (as this issue shows).
* The relative paths given to `rootcling` must be findable at dictionary generation time using the given `-I` paths.
* It makes some sense to use the same relative paths as used in `#include` in compiled code so that compiled and interpreted code can for example share the same include paths.
* The same relative paths must be findable at runtime using the same list (minus the `-excludePath` entries).
* This makes a common approach for developers (which usually want to work with stuff in the source/build tree and not install all the time) and package builders (where the source tree does not exist after installation and should never be referenced for security reasons) non trivial.
* One could add the install tree's include path to `rootcling` using `-I` and thus extend the stored path list in the dictionary and help the interpreter (we're doing this currently, see below). But in what order should one do that?
  * Putting the install tree first will possibly break developer experience (loading old headers from an outdated install tree). 
  * Putting the source tree first will possibly break installed modules if a different source tree exists in the original place (which could pose a security risk also!).

### My experience with vmc

I haven't yet looked into geant4_vmc (will likely come sooner than later), so I will explain, what we did for packaging vmc. Maybe this will help here a bit.

* vmc has only one include directory and projects seem to use straight things like `TMCManager.h` instead of prefixing with `vmc/`.
* So I concluded, to use the short names for dictionary generation (see: https://github.com/vmc-project/vmc/pull/8). This should not break anything that wasn't already broken, but will improve header search in the interpreter (using `$ROOT_INCLUDE_PATH`) and relocatability.
* I added the install tree's include directory using `ROOT_GENERATE_DICTIONARY … OPTIONS "-I${CMAKE_INSTALL_PREFIX}/include/${base_name}"` to the list in the dictionary.
* As we're targeting _packaging_, we don't want any source/build paths in the dictionary, so I have added a bunch of things like `-excludePath "${PROJECT_SOURCE_DIR}/source/include"` to `OPTIONS`

All in all this works very nicely for _packaging_.
I have not yet considered the last two points for a PR on vmc, as they are one answer to the above mentioned non trivial problem.

**Comment by dennisklein** [comment]
I think we can learn from [dynamic loader facilities](http://man7.org/linux/man-pages/man8/ld.so.8.html) here. Essentially, it offers the unprivileged user two configuration vectors for supplying the search path:

1. The `LD_LIBRARY_PATH` environment variable is added to the search path at run-time. 
2. A search path can be *burned* into the lib/exe artefacts at link-time. Additionally, the *burned* search path may contain tokens like `$ORIGIN` which are replaced at run-time by the loading entity which should be able to know where it loads the library from.

Vector 1 is already available with `ROOT_INCLUDE_PATH`.

Vector 2 is partially available. AFAIK there is nothing like the `$ORIGIN` token that would allow *burning* of relative search hints.

When I look how CMake e.g. accomplishes the *burning* of `RPATH/RUNPATH` entries, it essentially creates to different files for the build and install trees. The same approach could be taken here:
* Call `rootcling` twice with two different sets of `-I` arguments,
* generating two `dict_build_tree.cxx` and `dict_install_tree.cxx` files
* and then finally link together two libs (with only one of the cxx files above), one is put to the build tree and one is going to be installed.

This would be possible already now in theory - to be proven still. (With additional logic which is to be developed still, `rootcling` could help us here to not do too much work unnecessarily twice).

Resolving an `$ORIGIN` token in the *burned* search path at run-time also sounds doable IMHO, but may involve some development effort in ROOT.

**Comment by olifre** [comment]
@dennisklein That sounds like a very reasonable long-term solution to me. Just to complete hte information provided here, something similar is possible for debug symbols (see the [debugedit](https://manpages.ubuntu.com/manpages/bionic/man8/debugedit.8.html) tool) and some package managers (at least rpm and portage) make use of that to _burn_  the debug paths into the debug symbols upon installtion / relocation (or after splitting them out). 

Maybe it would be useful to open this proposal in [ROOTs bug tracker](https://sft.its.cern.ch/jira/projects/ROOT)? I'd certainly subscribe such an issue :-).

**Comment by olifre** [comment]
@ChristianTackeGSI Just out of curiosity, are you packaging for Debian / RHEL? 
I'm taking care of the packaging for Gentoo, which brought me here ;-). 

Thanks for the very nice compilation of observations, experiences and proposed solutions. Essentially, the first two points of your solution match "my" option 1 proposed in this thread, which also @ihrivnac considered the most straightforward solution. While 2a would be nice (and maybe also 2b), it would require quite some effort. 

So I agree (1) is the most straightforward approach, and taking into account that `g4root` and `mtroot` do not contain any dictionaries as Ivana pointed out, it should not bloat `ROOT_INCLUDE_PATH` too much. 

Indeed, solving the "non-trivial problem" which is left does not seem to have a clear answer. With distros such as Gentoo (not fully sure if it applies to others), you will have another problem when putting the install path first into the dictionaries: The new version may be compiled while an old version is already installed. The installed headers of older versions are visible during compilation, (that might e.g. be needed to solve dependency cycles, and stems from the fact that while "packaging" is sanboxed with namespaces in Gentoo, it still happens on the end users' machines and not in a minimal sandbox of a separate build machine). So _packaging_ at least for Gentoo would break when putting the installation path first. 

So for packaging the option to put the source tree first seems most reasonable, since this will be a temporary directory in any case. But that is sure to break developer workflows. 
So I don't have a good answer on this yet, but I'll keep pondering... in any case, the parts already in https://github.com/vmc-project/vmc/pull/8 look like the right approach to me. It also matches the behaviour of the old `geant-vmc`CMake macros which were now replaced with the macros provided by the ROOT project.

**Comment by ihrivnac** [comment]
Thank you all for you valuable comments. 

In addition to the changes in the PR already proposed, I would like to add  the point 3. in @ChristianTackeGSI experience with vmc list: "the install tree's include directory using ROOT_GENERATE_DICTIONARY … OPTIONS "-I${CMAKE_INSTALL_PREFIX}/include/${base_name}" to the list in the dictionary." what allows to run VMC test suite without setting ROOT_INCLUDE_PATH env variable.

Do you see any potential  relocability problems due to this setting?

**Comment by ChristianTackeGSI** [comment]
Hi @olifre,

I am packaging for spack. My packaging (including all the patches) is here: https://github.com/FairRootGroup/FairSoft/tree/dev/packages/vmc

Some notes:
* About the order:
  * I put the install directory last in the `-I`-list, so that during dictionary generation the local headers are used and the old ones in the install tree do not hurt.
  * For storing the path list, I use `-excludePath` to remove all the source/build paths from the search list. That way, only install paths are in there.
  * This stuff can be seen in the second part of `dict_fixes_101.patch` in my packaging tree.
* Having temporary paths in the list is a security risk: Those paths could be created by an attacker and another user's ROOT will load and interpret the code from those paths.

P.S.: I am just now working to fix the dictionary issue with geant4_vmc (basicly THIS issue). Let's see.

**Comment by ChristianTackeGSI** [comment]
Hi @ihrivnac,

if you want, I can add the »the install tree's include directory using `ROOT_GENERATE_DICTIONARY … OPTIONS "-I${CMAKE_INSTALL_PREFIX}/include/${base_name}"`« part to my PR on vmc? It's just one extra line (I'd put it in an extra commit for clarity).

About relocatability and the odds of this approach:
* If you move the library/dictionary to a new prefix, that new path's include directory obviously isn't in the path list in the dictionary. So in that case you have to use ROOT_INCLUDE_PATH (IMHO this is acceptable).
* If you forget to set ROOT_INCLUDE_PATH and there are still (incompatible) headers in the old install prefix, then those will be used. This is also IMHO acceptible: If you relocate things, you have to make sure, the old stuff is empty.
* Leaving the source/build trees in the dictionary leaves the above mentioned security risk. For development installs this is probably acceptable. For packaging (system use, etc) this is not acceptable.

**Comment by ihrivnac** [comment]
@ChristianTackeGSI , I've rebuild the vmc again  with your PR without the OPTIONS  and the VMC tests run fine without ROOT_INCLUDE_PATH  setting, what confirms your statements above that ROOT_GENERATE_DICTIONARY adds the source/build paths automatically. So I don't need to add this for my usual development mode. Otherwise I agree with your arguments that if we add the installation path it would make sense to exclude the other ones.

**Comment by ChristianTackeGSI** [comment]
Right, right, fine!

It could be argued that only adding the installation path to the end of the search list (using the `OPTIONS` thing) shouldn't hurt either: Because it only extends the list.
And it would improve the usage of the installed module.
In this area, I am really open to whatever works best for you.

For our packaging, I guess, we will stay with "append install path" + "remove _all_ source/build paths".

Let me know, if I should change, extend, etc. the PR.
(I am preparing an alike PR for geant4_vmc.)

**Comment by ihrivnac** [comment]
I have no strong opinion about this; as everything works as before without this addition, I have a slight preference for leaving it as it is in your PR now. 
I am now testing also the update in geant4_vmc and geant3, so there is no need to make a PR for this. When done, I will create the patch tags in all three packages.

**Comment by olifre** [comment]
Hi @ChristianTackeGSI ,

> I am packaging for spack. My packaging (including all the patches) is here: https://github.com/FairRootGroup/FairSoft/tree/dev/packages/vmc

Thanks, that's very helpful! 

>     * I put the install directory last in the `-I`-list, so that during dictionary generation the local headers are used and the old ones in the install tree do not hurt.

Indeed. This sounds like a reasonable way (combined with the excludes you describe) to be ensure safety and improve flexibility. 


> Leaving the source/build trees in the dictionary leaves the above mentioned security risk. For development installs this is probably acceptable. For packaging (system use, etc) this is not acceptable.

I think this is the major point here, and indeed I fully agree. While for most distro packaging this is an unlikely case (since those paths are in a sandboxed place which is accessible to root only), it's still explotiable if combined with another risk (or on a misconfigured system). 

So all in all, the approach:
`For our packaging, I guess, we will stay with "append install path" + "remove all source/build paths".`
which improves packaging and does not harm developers seems like the cleanest approach to me. 

@ihrivnac , I think also this approach would still leave everything functional exactly as before, but remove the potential security risks. So I'd call the existing PRs "restore the possibility to install and purge the build / source directories", and the remaining changes suggested by @ChristianTackeGSI  "improve security and clean up for packaging". 
What do you think?

**Comment by ihrivnac** [comment]
@olifre , it's ok for me to take the complete solution, too.
@ChristianTackeGSI , can you update your PR in VMC with both "append install path" + "remove all source/build paths" ?

**Comment by olifre** [comment]
@ihrivnac Thanks! That's really appreciated. Otherwise, any packaging would have needed to do exactly what the spack code linked by @ChristianTackeGSI does, and duplicating those patches downstream in all distros does not seem like a good idea. So it's for sure better to have the full solution here :-).

**Comment by ChristianTackeGSI** [comment]
I can extend my PR (probably on Monday).

Just one important note:
* For developers, this imposes a change! To use the created modules in the source/build tree, you _have_ to set ROOT_INCLUDE_PATH. Because the search path in the dictionary does no longer include the source/build paths.

Is this okay for you @ihrivnac ?

P.S.: This is exactly, what @dennisklein is planning to implement in FairRoot.

**Comment by olifre** [comment]
@ChristianTackeGSI Indeed, thanks for pointing this out! 
In my opinion, this is similar as to the need of specifying `LD_LIBRARY_PATH` to be able to run from the build tree, as is done now for the test suite (so setting `ROOT_INCLUDE_PATH` needs to be added there of course). For any development activity I do, I also always install to some prefix in my home directory, especially for libraries (such as these ones) for which the install tree layout often differs from the source / build tree, i.e. I'd never run from the actual build tree. 

So in my opinion, this is not an acual loss, but of course that's up to Ivana to decide.

**Comment by ihrivnac** [comment]
@ChristianTackeGSI , 
I run the test suites after complete installations, so it should not be a problem if the source/build paths are excluded. I will anyway run the tests before accepting the PR, so I will let you know in case of problems.

**Comment by ChristianTackeGSI** [comment]
Hi,

I have Improved https://github.com/vmc-project/vmc/pull/8 as discussed here.

Because I had the patches already prepared for our packaging, I have created #14. Feel free to do whatever is appropiate.

**Comment by ihrivnac** [comment]
@ChristianTackeGSI ,

Thank you. Your  PR in vmc is now merged. Your PR in Geant4 VMC is ok for me, too. 
The situation is a bit more complex for the examples, as the installation of examples is optional, and if selected, we install only examples libraries and executables. As the examples are not intended to be used in other project, I think, it would be more appropriate here just to remove the absolute path to headers without modifying the ROOT defaults with the OPTIONS.

So if this is fine both for @ChristianTackeGSI , @olifre , I will accept the PR #14 and update the examples as suggested above.

**Comment by ChristianTackeGSI** [comment]
@ihrivnac 

Thanks very much!
That sounds very good.
In fact, I didn't really know, what to do about the examples. So it's good, if you have a plan!

**Comment by olifre** [comment]
@ChristianTackeGSI Thanks from my side, too! 
Today is very loaded for me, I will try to give the current status for both projects a test run (with packaging and a framework using both) tonight,

**Comment by ihrivnac** [comment]
@olifre ,
Everything is now in place in master branches for all three packages. Please, take these in your tests. I will wait with tags for your feedback.

**Comment by olifre** [comment]
@ihrivnac Done, it works very well, and I also tested with the full framework I have access to (so I tested both vmc and geant-vmc) :-). 

For packaging for Gentoo, though, I see also have to run the test suite (@ChristianTackeGSI : Does Spack also have this concept?), and check it works without errors. Sadly, I see some failures for the interpreter-based suite (i.e. `test_suite.sh`) e of the following kind, e.g. in `E03/E03b/test_g4_tgeo_tgeo`:
```
...
Warning in <TInterpreter::ReadRootmapFile>: typedef  Ex03MCApplication found in libvmc_E03b.so  libvmc_E03c.so  libvmc_E03a.so  libvmc_E03a.so  libvmc_E03a.so  libvmc_E03a.so  libvmc_E06.so  libvmc_E03c.so  libvmc_E03a.so  libvmc_E03a.so  libvmc_E06.so  is already in libvmc_E03a.so 
...
Loading mtroot library ...
Warning in <TClassTable::Add>: class Ex03CalorHit already in TClassTable
Warning in <TClassTable::Add>: class Ex03PrimaryGenerator already in TClassTable
Warning in <TClassTable::Add>: class stack<TParticle*,deque<TParticle*> > already in TClassTable
libvmc_E03c dictionary forward declarations' payload:14:28: error: typedef redefinition with different types ('Ex03cMCApplication' vs 'Ex03MCApplication')
typedef Ex03cMCApplication Ex03MCApplication __attribute__((annotate("$clingAutoload$Ex03cMCApplication.h"))) ;
                           ^
libvmc_E03a dictionary forward declarations' payload:7:156: note: previous definition is here
class __attribute__((annotate(R"ATTRDUMP(Interface to MonteCarlo application)ATTRDUMP"))) __attribute__((annotate("$clingAutoload$Ex03MCApplication.h")))  Ex03MCApplication;
                                                                                                                                                           ^
root.exe: /var/tmp/portage/sci-physics/root-6.20.04/work/root-6.20.04/core/metacling/src/TCling.cxx:2072: virtual void TCling::RegisterModule(const char*, const char**, const char**, const char*, const char*, void (*)(), const FwdDeclArgsToKeepCollection_t&, const char**, Bool_t, Bool_t): Assertion `cling::Interpreter::kSuccess == compRes && "The forward declarations could not be compiled"' failed.
```
 
I think the cause is a different issue (and we can also of course take that to a new GitHub issue, but maybe that should still be changed before the next tag?): Multiple rootmaps created for the various examples contain clashing typedefs and forward declarations if visible to the ROOT interpreter at the same time. 

This issue has also been introduced as part of https://github.com/vmc-project/geant4_vmc/commit/d11d16421b965211d64a59bca1b50e51302b8147 : The `no_rootmap` feature supported by the old CMake macros saved us from hitting this. The ROOT macros seem to not support not writing out a rootmap, unless I am mistaken, so the libraries in `LD_LIBRARY_PATH` must not have conflicting declarations in their `rootmap` files. 

An easy "hack" I could put in packaging to workaround this is to do:
```
find "${BUILD_DIR}"/examples -name '*.rootmap' -delete
```
before running the test suite. That's a rather ugly hack, but after that, the test suite works for me,
Another "hack" would probably be to set `CMAKE_ROOTTEST_NOROOTMAP` to a truth value (which seems to be an undocumented "feature" of `RootMacros.cmake`) to avoid rootmap generation for all examples, but I have not tested that yet. 

In any case, the fact that the test suite works with this hack confirms that the issue reported here is fixed by the changes done by @ChristianTackeGSI :-). Thanks again!

**Comment by ChristianTackeGSI** [comment]
Thanks everybody!

About spack and running tests: Yes, spack has this concept. In parts it generates the unit tests for cmake based packages on its own and they're only optionally run if doing `spack install --run-tests` (or whatever the option was). In some of our packages, I run the tests manually and unconditionally.

About rootmaps: Maybe a cmake function like GEANT4_GENERATE_EXAMPLE_DICTIONARY that call ROOT_GENERATE_DICTIONARY and straight after that deletes the rootmap? Just pondering.

**Comment by ihrivnac** [comment]
Hi,

When adding  https://github.com/vmc-project/geant4_vmc/commit/d11d16421b965211d64a59bca1b50e51302b8147, I found out that the ROOT function does not provide an option to suppress generation of .rootmap file. As for my test suite (run from the installation) it is sufficient just not to install the .rootmap files, I did not search further how to suppress these files.

I will take a look how to address this in cmake as @ChristianTackeGSI suggests.

**Comment by ihrivnac** [comment]
@olifre ,
Could you try out with the new commit  https://github.com/vmc-project/geant4_vmc/commit/84e9921f2b8b1da3bff52e61e9c81095779232a2 ?
There is added a clean-up of examples rootmap's.

**Comment by olifre** [comment]
@ihrivnac Perfect, that works without any issues for me :-). 
I did not know about `POST_BUILD` commands before, that looks like a nice solution, thanks for implementing this so quickly!

**Comment by ihrivnac** [comment]
@olifre , thank you for testing.
The fixes are now available in the following versions:
vmc - 1.0.p2,  geant3 - 3.4,  geant4_vmc - 5.0.p3 (based on Geant4 10.5.x) and  5.1.p1 (based on Geant4 10.6.x)
